param(
    [Parameter(Mandatory = $true)]
    [string]$Updater,
    [Parameter(Mandatory = $true)]
    [string]$Output
)

$ErrorActionPreference = "Stop"

function Convert-ToCppBytes {
    param([byte[]]$Bytes)

    if (!$Bytes -or $Bytes.Length -eq 0) {
        return "    0x00"
    }

    $lines = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $Bytes.Length; $i += 16) {
        $end = [Math]::Min($i + 15, $Bytes.Length - 1)
        $parts = for ($j = $i; $j -le $end; ++$j) {
            "0x{0:X2}" -f $Bytes[$j]
        }
        $lines.Add("    " + ($parts -join ", "))
    }
    return $lines -join ",`n"
}

$updaterPath = (Resolve-Path -LiteralPath $Updater).Path
$outputPath = [System.IO.Path]::GetFullPath($Output)
$outputDir = Split-Path -Parent $outputPath
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

$bytes = [System.IO.File]::ReadAllBytes($updaterPath)

$content = New-Object System.Collections.Generic.List[string]
$content.Add("// Generated by tools/generate-embedded-updater.ps1. Do not edit manually.") | Out-Null
$content.Add('#include "EmbeddedUpdater.h"') | Out-Null
$content.Add("") | Out-Null
$content.Add("#include <cstddef>") | Out-Null
$content.Add("") | Out-Null
$content.Add("namespace {") | Out-Null
$content.Add("const unsigned char kEmbeddedUpdater[] = {") | Out-Null
$content.Add((Convert-ToCppBytes -Bytes $bytes)) | Out-Null
$content.Add("};") | Out-Null
$content.Add("}") | Out-Null
$content.Add("") | Out-Null
$content.Add("const unsigned char* EmbeddedUpdaterData() {") | Out-Null
$content.Add("    return kEmbeddedUpdater;") | Out-Null
$content.Add("}") | Out-Null
$content.Add("") | Out-Null
$content.Add("std::size_t EmbeddedUpdaterSize() {") | Out-Null
$content.Add("    return sizeof(kEmbeddedUpdater);") | Out-Null
$content.Add("}") | Out-Null

[System.IO.File]::WriteAllText($outputPath, ($content -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
