param(
    [Parameter(Mandatory = $true)]
    [string]$Executable,
    [Parameter(Mandatory = $true)]
    [string]$Output,
    [Parameter(Mandatory = $true)]
    [string]$Symbol,
    [Parameter(Mandatory = $true)]
    [string]$Id,
    [Parameter(Mandatory = $true)]
    [string]$FileName,
    [Parameter(Mandatory = $true)]
    [string]$ExpectedVersion
)

$ErrorActionPreference = "Stop"

function Convert-ToCppBytes {
    param([byte[]]$Bytes)

    if (!$Bytes -or $Bytes.Length -eq 0) {
        return "    0x00"
    }

    $lines = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $Bytes.Length; $i += 16) {
        $end = [Math]::Min($i + 15, $Bytes.Length - 1)
        $parts = for ($j = $i; $j -le $end; ++$j) {
            "0x{0:X2}" -f $Bytes[$j]
        }
        $lines.Add("    " + ($parts -join ", ")) | Out-Null
    }
    return $lines -join ",`n"
}

function Convert-ToCppWideLiteral {
    param([string]$Value)

    return 'L"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

if ($Symbol -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
    throw "Invalid C++ symbol: $Symbol"
}

$executablePath = (Resolve-Path -LiteralPath $Executable).Path
$outputPath = [System.IO.Path]::GetFullPath($Output)
$outputDir = Split-Path -Parent $outputPath
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

$versionInfo = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($executablePath)
$actualVersion = $versionInfo.ProductVersion
if ([string]::IsNullOrWhiteSpace($actualVersion)) {
    $actualVersion = $versionInfo.FileVersion
}
if ($actualVersion -ne $ExpectedVersion) {
    throw "Embedded executable version mismatch: $executablePath reports '$actualVersion', expected '$ExpectedVersion'."
}

$bytes = [System.IO.File]::ReadAllBytes($executablePath)
$sha256Provider = [System.Security.Cryptography.SHA256]::Create()
try {
    $sha256 = ([System.BitConverter]::ToString($sha256Provider.ComputeHash($bytes))).Replace("-", "").ToLowerInvariant()
} finally {
    $sha256Provider.Dispose()
}

$content = New-Object System.Collections.Generic.List[string]
$content.Add("// Generated by tools/generate-embedded-executable.ps1. Do not edit manually.") | Out-Null
$content.Add('#include "EmbeddedExecutable.h"') | Out-Null
$content.Add("") | Out-Null
$content.Add("#include <cstddef>") | Out-Null
$content.Add("") | Out-Null
$content.Add("namespace {") | Out-Null
$content.Add("const unsigned char kEmbedded${Symbol}Data[] = {") | Out-Null
$content.Add((Convert-ToCppBytes -Bytes $bytes)) | Out-Null
$content.Add("};") | Out-Null
$content.Add("}") | Out-Null
$content.Add("") | Out-Null
$content.Add("const EmbeddedExecutableDescriptor& EmbeddedExecutable_${Symbol}() {") | Out-Null
$content.Add("    static const EmbeddedExecutableDescriptor descriptor{") | Out-Null
$content.Add("        $(Convert-ToCppWideLiteral -Value $Id),") | Out-Null
$content.Add("        $(Convert-ToCppWideLiteral -Value $FileName),") | Out-Null
$content.Add("        $(Convert-ToCppWideLiteral -Value $ExpectedVersion),") | Out-Null
$content.Add("        $(Convert-ToCppWideLiteral -Value $sha256),") | Out-Null
$content.Add("        kEmbedded${Symbol}Data,") | Out-Null
$content.Add("        sizeof(kEmbedded${Symbol}Data),") | Out-Null
$content.Add("    };") | Out-Null
$content.Add("    return descriptor;") | Out-Null
$content.Add("}") | Out-Null

[System.IO.File]::WriteAllText($outputPath, ($content -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
