param(
    [Parameter(Mandatory = $true)]
    [string]$Root,
    [Parameter(Mandatory = $true)]
    [string]$Output
)

$ErrorActionPreference = "Stop"

function Convert-ToCppString {
    param([string]$Value)

    $escaped = $Value.Replace("\", "\\").Replace('"', '\"')
    return "L`"$escaped`""
}

function Convert-ToCppBytes {
    param([byte[]]$Bytes)

    if (!$Bytes -or $Bytes.Length -eq 0) {
        return "    0x00"
    }

    $lines = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $Bytes.Length; $i += 16) {
        $end = [Math]::Min($i + 15, $Bytes.Length - 1)
        $parts = for ($j = $i; $j -le $end; ++$j) {
            "0x{0:X2}" -f $Bytes[$j]
        }
        $lines.Add("    " + ($parts -join ", "))
    }
    return $lines -join ",`n"
}

$rootPath = (Resolve-Path -LiteralPath $Root).Path
$rootPrefix = $rootPath.TrimEnd("\") + "\"
$outputPath = [System.IO.Path]::GetFullPath($Output)
$outputDir = Split-Path -Parent $outputPath
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

$relativeFiles = New-Object System.Collections.Generic.List[string]
foreach ($file in @("README.md")) {
    $path = Join-Path $rootPath $file
    if (Test-Path -LiteralPath $path) {
        $relativeFiles.Add($file.Replace("/", "\")) | Out-Null
    }
}

foreach ($dir in @("theme", "icons/url", "docs")) {
    $path = Join-Path $rootPath $dir
    if (Test-Path -LiteralPath $path) {
        Get-ChildItem -LiteralPath $path -Recurse -File |
            Sort-Object FullName |
            ForEach-Object {
                $fullName = $_.FullName
                if ($fullName.StartsWith($rootPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                    $relative = $fullName.Substring($rootPrefix.Length)
                } else {
                    $relative = $_.Name
                }
                $relativeFiles.Add($relative) | Out-Null
            }
    }
}

$content = New-Object System.Collections.Generic.List[string]
$content.Add("// Generated by tools/generate-embedded-assets.ps1. Do not edit manually.") | Out-Null
$content.Add('#include "EmbeddedAssets.h"') | Out-Null
$content.Add("") | Out-Null
$content.Add("#include <cstddef>") | Out-Null
$content.Add("") | Out-Null
$content.Add("namespace {") | Out-Null

$assets = New-Object System.Collections.Generic.List[string]
for ($i = 0; $i -lt $relativeFiles.Count; ++$i) {
    $relative = $relativeFiles[$i]
    $fullPath = Join-Path $rootPath $relative
    $bytes = [System.IO.File]::ReadAllBytes($fullPath)
    $symbol = "kEmbeddedAsset_$i"
    $content.Add("const unsigned char $symbol[] = {") | Out-Null
    $content.Add((Convert-ToCppBytes -Bytes $bytes)) | Out-Null
    $content.Add("};") | Out-Null
    $content.Add("") | Out-Null
    $assets.Add("    { $(Convert-ToCppString -Value $relative), $symbol, sizeof($symbol) }") | Out-Null
}

$content.Add("const EmbeddedAsset kEmbeddedAssets[] = {") | Out-Null
if ($assets.Count -gt 0) {
    $content.Add(($assets -join ",`n")) | Out-Null
}
$content.Add("};") | Out-Null
$content.Add("}") | Out-Null
$content.Add("") | Out-Null
$content.Add("std::size_t EmbeddedAssetCount() {") | Out-Null
$content.Add("    return sizeof(kEmbeddedAssets) / sizeof(kEmbeddedAssets[0]);") | Out-Null
$content.Add("}") | Out-Null
$content.Add("") | Out-Null
$content.Add("const EmbeddedAsset& EmbeddedAssetAt(std::size_t index) {") | Out-Null
$content.Add("    return kEmbeddedAssets[index];") | Out-Null
$content.Add("}") | Out-Null

[System.IO.File]::WriteAllText($outputPath, ($content -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
