param(
    [Parameter(Mandatory = $true)]
    [string]$InputFont,
    [Parameter(Mandatory = $true)]
    [string]$OutputFont,
    [Parameter(Mandatory = $true)]
    [string]$Codepoints
)

$ErrorActionPreference = "Stop"
$inputPath = [System.IO.Path]::GetFullPath($InputFont)
$outputPath = [System.IO.Path]::GetFullPath($OutputFont)
$codepointsPath = [System.IO.Path]::GetFullPath($Codepoints)
if (!(Test-Path -LiteralPath $inputPath)) {
    throw "Tabler source font not found: $inputPath"
}
if (!(Test-Path -LiteralPath $codepointsPath)) {
    throw "Tabler codepoint manifest not found: $codepointsPath"
}

$python = Get-Command python.exe -ErrorAction SilentlyContinue
if (!$python) {
    throw "Python is required to validate and subset the Tabler runtime font."
}
$unicodes = @(
    Get-Content -LiteralPath $codepointsPath |
        Where-Object { ![string]::IsNullOrWhiteSpace($_) } |
        ForEach-Object { $_.Trim() }
) -join ","
if ([string]::IsNullOrWhiteSpace($unicodes)) {
    throw "Tabler codepoint manifest is empty."
}
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outputPath) | Out-Null
$arguments = @(
    "-m", "fontTools.subset", $inputPath,
    "--output-file=$outputPath",
    "--unicodes=$unicodes",
    "--no-ignore-missing-unicodes",
    "--layout-features=*",
    "--symbol-cmap",
    "--legacy-cmap",
    "--notdef-glyph",
    "--recommended-glyphs",
    "--name-IDs=*",
    "--name-languages=*"
)
& $python.Source @arguments
if ($LASTEXITCODE -ne 0 -or !(Test-Path -LiteralPath $outputPath)) {
    throw "Failed to subset Tabler font."
}
"tabler_font_subset=generated bytes=$((Get-Item -LiteralPath $outputPath).Length)"
